events {}

http {
    server {
        listen 80;
        server_name _;

        root /data;

        location /releases/ {
            types {
                application/xml xml;
                application/java-archive jar;
            }
            default_type application/octet-stream;
            autoindex on;
        }

        location /snapshots/ {
            types {
                application/xml xml;
                application/java-archive jar;
            }
            default_type application/octet-stream;
            autoindex on;
        }

        location / {
            return 404;
        }
    }
}
