github:
  token: ${GITHUB_TOKEN}

artifactory:
  base-url: ${ARTIFACTORY_BASE_URL:}
  release-repo: ${ARTIFACTORY_RELEASE_REPO:}
  snapshot-repo: ${ARTIFACTORY_SNAPSHOT_REPO:}
  token: ${ARTIFACTORY_TOKEN:}

logging:
  level:
    com.depresolver: DEBUG
