repos:
  - url: https://github.com/francis007-del-01/core-lib
    triggerBranch: main

  - url: https://github.com/francis007-del-01/utils
    triggerBranch: main

  - url: https://github.com/francis007-del-01/test-service-b
    targetBranches:
      - name: main
        autoMerge: false
      - name: develop
        autoMerge: true

  - url: https://github.com/francis007-del-01/test-service-c
    targetBranches:
      - name: main
        autoMerge: false
